// Default warehouse seed data, ported from the former bubblena-admin localStorage seeds.
// All quantities are in GRAMS (former "ml" values are kept numerically, 1 ml ≈ 1 g).

export const SEED_MATERIALS: string[] = [
  'Aktivní uhlí',
  'Aqua',
  'Cocamidopropyl Betaine',
  'EO bergamot',
  'EO levandule',
  'EO santal',
  'EO višeň a švestka',
  'EO černý bez',
  'FO broskev',
  'FO pomeranč',
  'Glitry stříbrné',
  'Glycerinové barvivo fialová',
  'Glycerinové barvivo modrá',
  'Glycerinové barvivo oranžová',
  'Glycerinové barvivo růžová',
  'Glycerinové barvivo fialová EXTRA',
  'Hrubozrná sůl',
  'Jedlá soda',
  'Kokosový olej',
  'Kukuřičný škrob',
  'Kyselina citronová',
  'MICA blueberry',
  'MICA deep ocean',
  'MICA red orange',
  'MICA rosegold',
  'MICA soft ametyst',
  'MICA sunbeam',
  'MICA super orange',
  'MICA warmspice',
  'P80',
  'SLES',
  'SLSA',
  'Sléz květ',
  'Sušené mléko',
  'Sušený měsíček',
  'Sůl Epsomská',
  'Sůl z mrtvého moře',
  'Vanilka - parfémová kompozice',
  'Vonný olej - kokos',
]

export const SEED_STOCK: { materialName: string; batchNumber: string; quantity: number; dateStocked: string }[] = [
  { materialName: 'Glitry stříbrné', batchNumber: '3349G', quantity: 106, dateStocked: '2026-01-01' },
  { materialName: 'Hrubozrná sůl', batchNumber: '240808', quantity: 250, dateStocked: '2026-01-01' },
  { materialName: 'Jedlá soda', batchNumber: 'SOP-007', quantity: 20000, dateStocked: '2026-01-01' },
  { materialName: 'Kokosový olej', batchNumber: 'L161368', quantity: 5000, dateStocked: '2026-01-01' },
  { materialName: 'Kukuřičný škrob', batchNumber: '170825', quantity: 6000, dateStocked: '2026-01-01' },
  { materialName: 'Kyselina citronová', batchNumber: 'A22412004', quantity: 5000, dateStocked: '2026-01-01' },
  { materialName: 'MICA rosegold', batchNumber: '11514', quantity: 53, dateStocked: '2026-01-01' },
  { materialName: 'MICA sunbeam', batchNumber: '1842663', quantity: 40, dateStocked: '2026-01-01' },
  { materialName: 'P80', batchNumber: '4744', quantity: 100, dateStocked: '2026-01-01' },
  { materialName: 'SLSA', batchNumber: '9228997', quantity: 400, dateStocked: '2026-01-01' },
  { materialName: 'Vanilka - parfémová kompozice', batchNumber: 'PK251439', quantity: 30, dateStocked: '2026-01-01' },
  { materialName: 'Vonný olej - kokos', batchNumber: 'PK258572', quantity: 50, dateStocked: '2026-01-01' },
  { materialName: 'Glycerinové barvivo fialová EXTRA', batchNumber: '31012027', quantity: 50, dateStocked: '2026-01-01' },
]

export const SEED_RECIPES: { name: string; acronym: string; ingredients: { materialName: string; quantity: number }[] }[] = [
  {
    name: 'Blossan',
    acronym: 'BLS',
    ingredients: [
      { materialName: 'Jedlá soda', quantity: 750 },
      { materialName: 'Kyselina citronová', quantity: 300 },
      { materialName: 'Kukuřičný škrob', quantity: 60 },
      { materialName: 'Kokosový olej', quantity: 9 },
      { materialName: 'EO santal', quantity: 9 },
      { materialName: 'Sůl Epsomská', quantity: 30 },
      { materialName: 'SLES', quantity: 12 },
      { materialName: 'MICA soft ametyst', quantity: 3 },
      { materialName: 'Sléz květ', quantity: 2.1 },
      { materialName: 'P80', quantity: 9 },
      { materialName: 'Glycerinové barvivo fialová EXTRA', quantity: 2.3 },
    ],
  },
  {
    name: 'Kokobana',
    acronym: 'KB',
    ingredients: [
      { materialName: 'Jedlá soda', quantity: 750 },
      { materialName: 'Kyselina citronová', quantity: 300 },
      { materialName: 'Kukuřičný škrob', quantity: 90 },
      { materialName: 'Vonný olej - kokos', quantity: 12 },
      { materialName: 'Vanilka - parfémová kompozice', quantity: 6 },
      { materialName: 'SLSA', quantity: 9 },
      { materialName: 'MICA sunbeam', quantity: 3.5 },
      { materialName: 'MICA rosegold', quantity: 0.9 },
      { materialName: 'Glitry stříbrné', quantity: 6 },
      { materialName: 'P80', quantity: 12 },
      { materialName: 'Aqua', quantity: 7.5 },
      { materialName: 'Hrubozrná sůl', quantity: 38 },
    ],
  },
  {
    name: 'Noirvana',
    acronym: 'NV',
    ingredients: [
      { materialName: 'Jedlá soda', quantity: 735 },
      { materialName: 'Kyselina citronová', quantity: 294 },
      { materialName: 'Kukuřičný škrob', quantity: 42 },
      { materialName: 'Kokosový olej', quantity: 19.5 },
      { materialName: 'EO bergamot', quantity: 4.5 },
      { materialName: 'EO černý bez', quantity: 4.5 },
      { materialName: 'Sůl z mrtvého moře', quantity: 15 },
      { materialName: 'Sušené mléko', quantity: 30 },
      { materialName: 'Aktivní uhlí', quantity: 6 },
      { materialName: 'Sušený měsíček', quantity: 1 },
      { materialName: 'P80', quantity: 12.5 },
      { materialName: 'Cocamidopropyl Betaine', quantity: 9 },
    ],
  },
  {
    name: 'Blue orbit',
    acronym: 'BO',
    ingredients: [
      { materialName: 'Jedlá soda', quantity: 750 },
      { materialName: 'Kyselina citronová', quantity: 300 },
      { materialName: 'Kukuřičný škrob', quantity: 90 },
      { materialName: 'SLSA', quantity: 12 },
      { materialName: 'MICA deep ocean', quantity: 1.5 },
      { materialName: 'MICA blueberry', quantity: 1.5 },
      { materialName: 'Glitry stříbrné', quantity: 3 },
      { materialName: 'EO višeň a švestka', quantity: 12 },
      { materialName: 'Kokosový olej', quantity: 6 },
      { materialName: 'Aqua', quantity: 7 },
      { materialName: 'Glycerinové barvivo modrá', quantity: 2.3 },
      { materialName: 'Glycerinové barvivo fialová', quantity: 2.3 },
      { materialName: 'P80', quantity: 12 },
    ],
  },
  {
    name: 'Summer madness',
    acronym: 'SM',
    ingredients: [
      { materialName: 'Jedlá soda', quantity: 690 },
      { materialName: 'Kyselina citronová', quantity: 276 },
      { materialName: 'Kukuřičný škrob', quantity: 105.8 },
      { materialName: 'MICA warmspice', quantity: 2.3 },
      { materialName: 'MICA red orange', quantity: 2.3 },
      { materialName: 'MICA super orange', quantity: 2.3 },
      { materialName: 'FO broskev', quantity: 6.9 },
      { materialName: 'FO pomeranč', quantity: 6.9 },
      { materialName: 'Kokosový olej', quantity: 4.6 },
      { materialName: 'Glycerinové barvivo růžová', quantity: 1.5 },
      { materialName: 'Glycerinové barvivo oranžová', quantity: 1.5 },
      { materialName: 'P80', quantity: 13.8 },
      { materialName: 'Cocamidopropyl Betaine', quantity: 9.2 },
    ],
  },
  {
    name: 'Steamer levandule',
    acronym: 'SL',
    ingredients: [
      { materialName: 'Jedlá soda', quantity: 124 },
      { materialName: 'Kyselina citronová', quantity: 71 },
      { materialName: 'Kokosový olej', quantity: 3 },
      { materialName: 'EO levandule', quantity: 6 },
    ],
  },
]
